In [0]:
#https://www.tensorflow.org/tutorials/load_data/pandas_dataframe
#Load a pandas.DataFrame
#Load pandas dataframes into a tf.data.Dataset.
#Como que tf.data.Dataset es la unidad básica, y se le pasa esto a los modelos

In [2]:
from __future__ import absolute_import, division, print_function, unicode_literals

# TensorFlow and tf.keras
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf
from tensorflow import keras
import numpy as np

TensorFlow 2.x selected.


In [0]:
import pandas as pd

In [4]:
csv_file = tf.keras.utils.get_file('heart.csv', 'https://storage.googleapis.com/applied-dl/heart.csv')


16384/13273 [=====================================] - 0s 0us/step


In [0]:
csv_file #This is the file, but it has to be read
df = pd.read_csv(csv_file)


In [6]:
df #We get a pandas dataframe

age  sex  cp  trestbps  chol  ...  oldpeak  slope  ca        thal  target
0     63    1   1       145   233  ...      2.3      3   0       fixed       0
1     67    1   4       160   286  ...      1.5      2   3      normal       1
2     67    1   4       120   229  ...      2.6      2   2  reversible       0
3     37    1   3       130   250  ...      3.5      3   0      normal       0
4     41    0   2       130   204  ...      1.4      1   0      normal       0
..   ...  ...  ..       ...   ...  ...      ...    ...  ..         ...     ...
298   52    1   1       118   186  ...      0.0      2   0       fixed       0
299   43    0   4       132   341  ...      3.0      2   0  reversible       1
300   65    1   4       135   254  ...      2.8      2   1  reversible       1
301   48    1   4       130   256  ...      0.0      1   2  reversible       1
302   63    0   4       150   407  ...      4.0      2   3  reversible       1

[303 rows x 14 columns]

In [7]:
df.dtypes #Check the types of data

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal         object
target        int64
dtype: object

In [0]:
df['thal'] = pd.Categorical(df['thal'])
df['thal'] = df.thal.cat.codes #Transform thal into integers. ISSUE: is this not bad? should we use one-hot insted?
#because integers like this mean a relation between the numbers, not a category?

In [9]:
df

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0     63    1   1       145   233    1  ...      0      2.3      3   0     2       0
1     67    1   4       160   286    0  ...      1      1.5      2   3     3       1
2     67    1   4       120   229    0  ...      1      2.6      2   2     4       0
3     37    1   3       130   250    0  ...      0      3.5      3   0     3       0
4     41    0   2       130   204    0  ...      0      1.4      1   0     3       0
..   ...  ...  ..       ...   ...  ...  ...    ...      ...    ...  ..   ...     ...
298   52    1   1       118   186    0  ...      0      0.0      2   0     2       0
299   43    0   4       132   341    1  ...      1      3.0      2   0     4       1
300   65    1   4       135   254    0  ...      0      2.8      2   1     4       1
301   48    1   4       130   256    1  ...      1      0.0      1   2     4       1
302   63    0   4       150   407    0  ...      0      4.0      2   3     4       1

[303 rows x 14 columns]

In [0]:
#Load data using tf.data.Dataset #I should read the documentation:  https://www.tensorflow.org/api_docs/python/tf/data/Dataset
#Use tf.data.Dataset.from_tensor_slices to read the values from a pandas dataframe. 
#NOTE: after tutorials, there are guides, eg. https://www.tensorflow.org/guide/data   <- data guide. Do those next.
target = df.pop('target') #NOTE: cannot run this cell twice because the df now does not have the 'target column'
dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values)) #This places the labels and the values together

In [11]:
dataset #Because we have not batched it, it only has the 13, as shape

<TensorSliceDataset shapes: ((13,), ()), types: (tf.float64, tf.int64)>

In [12]:
for feat, targ in dataset.take(5): #Because dataset has 'two sets?' we can use the for loop
  print ('Features: {}, Target: {}'.format(feat, targ)) #we take 5 of the features (5 rows)


Features: [ 63.    1.    1.  145.  233.    1.    2.  150.    0.    2.3   3.    0.
   2. ], Target: 0
Features: [ 67.    1.    4.  160.  286.    0.    2.  108.    1.    1.5   2.    3.
   3. ], Target: 1
Features: [ 67.    1.    4.  120.  229.    0.    2.  129.    1.    2.6   2.    2.
   4. ], Target: 0
Features: [ 37.    1.    3.  130.  250.    0.    0.  187.    0.    3.5   3.    0.
   3. ], Target: 0
Features: [ 41.    0.    2.  130.  204.    0.    2.  172.    0.    1.4   1.    0.
   3. ], Target: 0


In [13]:
#NOTE: Since a pd.Series implements the __array__ protocol it can be used transparently nearly anywhere you would use a np.array or a tf.Tensor.
tf.constant(df['thal']) #Take every value? of the column thal


<tf.Tensor: shape=(303,), dtype=int32, numpy=
array([2, 3, 4, 3, 3, 3, 3, 3, 4, 4, 2, 3, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3,
       3, 4, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 4, 2, 4, 3, 4, 3, 4, 4,
       2, 3, 3, 4, 3, 3, 4, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 4,
       4, 2, 3, 3, 4, 3, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 3, 3, 4, 4, 4,
       3, 3, 4, 3, 4, 4, 3, 4, 3, 3, 3, 4, 3, 4, 4, 3, 3, 4, 4, 4, 4, 4,
       3, 3, 3, 3, 4, 3, 4, 3, 4, 4, 3, 3, 2, 4, 4, 2, 3, 3, 4, 4, 3, 4,
       3, 3, 4, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 3, 2,
       4, 4, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 2, 2, 4, 3, 4, 2, 4, 3,
       3, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 2, 2, 4, 3, 4, 3, 2, 4, 3, 3, 2,
       4, 4, 4, 4, 3, 0, 3, 3, 3, 3, 1, 4, 3, 3, 3, 4, 3, 4, 3, 3, 3, 4,
       3, 3, 4, 4, 4, 4, 3, 3, 4, 3, 4, 3, 4, 4, 3, 4, 4, 3, 4, 4, 3, 3,
     

In [0]:
#Shuffle and batch the dataset
train_dataset = dataset.shuffle(len(df)).batch(1)


#Steps to make a dataset:

1. use:
```
dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values))#This places the labels and the values together
```
to build the dataset with the values and the target:

2. use:
```
train_dataset = dataset.shuffle(len(df)).batch(1) #Shuffle and batch the dataset
```
to make the dataset (shuffled) in batches to be able to pass it properly to the model






In [15]:
(train_dataset) #This is a dataset ..that has batches?


<BatchDataset shapes: ((None, 13), (None,)), types: (tf.float64, tf.int64)>

In [0]:
#Create and train model
def get_compiled_model(): #Building a function to get the model already copiled
  model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
  ])

  model.compile(optimizer='adam',
                loss='binary_crossentropy',
                metrics=['accuracy'])
  return model

In [19]:
model = get_compiled_model()
model.fit(train_dataset, epochs=15)
model.summary()

Train for 303 steps
Epoch 1/15
303/303 [==============================] - 1s 4ms/step - loss: 1.3435 - accuracy: 0.6601
Epoch 2/15
303/303 [==============================] - 1s 3ms/step - loss: 0.6934 - accuracy: 0.6931
Epoch 3/15
303/303 [==============================] - 1s 3ms/step - loss: 0.6777 - accuracy: 0.7162
Epoch 4/15
303/303 [==============================] - 1s 3ms/step - loss: 0.7094 - accuracy: 0.7063
Epoch 5/15
303/303 [==============================] - 1s 3ms/step - loss: 0.7019 - accuracy: 0.6997
Epoch 6/15
303/303 [==============================] - 1s 3ms/step - loss: 0.6389 - accuracy: 0.6997
Epoch 7/15
303/303 [==============================] - 1s 3ms/step - loss: 0.6399 - accuracy: 0.7063
Epoch 8/15
303/303 [==============================] - 1s 3ms/step - loss: 0.6274 - accuracy: 0.7195
Epoch 9/15
303/303 [==============================] - 1s 3ms/step - loss: 0.6367 - accuracy: 0.7261
Epoch 10/15
303/303 [==============================] - 1s 3ms/step - loss: 0.583

In [25]:
predictions = model.predict(train_dataset) #Aqui te da un array con todas las predicciones #las 303
predictions.shape #las predicciones son de 0 a 1 parece, aunque aquí la max es .4


(303, 1)

#Alternative to feature columns

Passing a dictionary as an input to a model is as easy as creating a matching dictionary of tf.keras.layers.Input layers, applying any pre-processing and stacking them up using the functional api. You can use this as an alternative to feature columns.

In [0]:
#Basically doing the same but using a dictionary as column (feature) names?
inputs = {key: tf.keras.layers.Input(shape=(), name=key) for key in df.keys()}
x = tf.stack(list(inputs.values()), axis=-1)

x = tf.keras.layers.Dense(10, activation='relu')(x)
output = tf.keras.layers.Dense(1, activation='sigmoid')(x)

model_func = tf.keras.Model(inputs=inputs, outputs=output)

model_func.compile(optimizer='adam',
                   loss='binary_crossentropy',
                   metrics=['accuracy'])


The easiest way to preserve the column structure of a pd.DataFrame when used with tf.data is to convert the pd.DataFrame to a dict, and slice that dictionary.

In [28]:
dict_slices = tf.data.Dataset.from_tensor_slices((df.to_dict('list'), target.values)).batch(16) #This is a batch dataset
for dict_slice in dict_slices.take(1): #take one batch, of 16, it has 16 'rows' of the attributes
  print (dict_slice)


({'age': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([63, 67, 67, 37, 41, 56, 62, 57, 63, 53, 57, 56, 56, 44, 52, 57],
      dtype=int32)>, 'sex': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1], dtype=int32)>, 'cp': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 4, 4, 3, 2, 2, 4, 4, 4, 4, 4, 2, 3, 2, 3, 3], dtype=int32)>, 'trestbps': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([145, 160, 120, 130, 130, 120, 140, 120, 130, 140, 140, 140, 130,
       120, 172, 150], dtype=int32)>, 'chol': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([233, 286, 229, 250, 204, 236, 268, 354, 254, 203, 192, 294, 256,
       263, 199, 168], dtype=int32)>, 'fbs': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int32)>, 'restecg': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0, 0], dtype=int32)>, 'thalach': <tf.Tensor: shape=(16

In [32]:
model_func.fit(dict_slices, epochs=15)
#Same fitting, just with this new way of building the data

Train for 19 steps
Epoch 1/15
19/19 [==============================] - 0s 4ms/step - loss: 1.2518 - accuracy: 0.6403
Epoch 2/15
19/19 [==============================] - 0s 4ms/step - loss: 1.2053 - accuracy: 0.6370
Epoch 3/15
19/19 [==============================] - 0s 4ms/step - loss: 1.1621 - accuracy: 0.6469
Epoch 4/15
19/19 [==============================] - 0s 4ms/step - loss: 1.1222 - accuracy: 0.6634
Epoch 5/15
19/19 [==============================] - 0s 4ms/step - loss: 1.0855 - accuracy: 0.6700
Epoch 6/15
19/19 [==============================] - 0s 4ms/step - loss: 1.0518 - accuracy: 0.6634
Epoch 7/15
19/19 [==============================] - 0s 4ms/step - loss: 1.0209 - accuracy: 0.6733
Epoch 8/15
19/19 [==============================] - 0s 4ms/step - loss: 0.9926 - accuracy: 0.6733
Epoch 9/15
19/19 [==============================] - 0s 4ms/step - loss: 0.9664 - accuracy: 0.6733
Epoch 10/15
19/19 [==============================] - 0s 4ms/step - loss: 0.9426 - accuracy: 0.6799
